### ISSUE TITLE
某个菜逼的建议

### ISSUE THREAD

**Issue by FloppyDisk-FD** [1478599553/Minecraft_1.16_ModTranslationgResourcePack#3]
# 能不能搞个Weblate，这么fork,pr有点蛋疼

**Comment by 1478599553** [comment]
我在搞了，过几天就行，git挺好的（关键你也没有任何贡献啊（（（不是

**Comment by FloppyDisk-FD** [comment]
> 我在搞了，过几天就行，git挺好的（关键你也没有任何贡献啊（（（不是

在翻了在翻了，不要这么说嘛，我已经尽力在翻了
